fix: selinux: use kernel definition of PF_MAX in scripts
Building selinux scripts of old releases on a current host fails with:
	In file included from scripts/selinux/genheaders/genheaders.c:19:
      ./security/selinux/include/classmap.h:245:2: error: #error New
      address family defined, please update secclass_map.

 Fix the issue by including linux/socket.h from kernel instead of
sys/socket.h from host.

https://patchwork.kernel.org/project/selinux/patch/20190312194758.6f411a8b@t440s.fritz.box/

Signed-off-by: Johannes Brechtmann <johannes@jnbr.me>